### ISSUE TITLE
MP photos in twitter cards be peeking

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#1005]
Well hello there.

![selection_001](https://cloud.githubusercontent.com/assets/48945/5310161/4a977f0a-7c82-11e4-8f4a-9115aa9f0e2f.png)

**Comment by equivalentideas** [comment]
Doesn't seems to be an issue on twitter anymore: https://twitter.com/search?f=tweets&vertical=default&q=theyvoteforyou&src=typd
