### ISSUE TITLE
3 ways to keep TheyVoteForYou tickety boo

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1047]
Managing TheyVoteForYou can be time consuming. So, I've prioritised the three most important jobs to make it a little easier. 

If these three tasks are done regularly, the site will remain tickety boo (which is urban slang for 'useful and current').

### Priority 1: Manage the policies

Firstly, mark any **problematic policies** as drafts. Problematic policies are, for example:
* Biased (i.e. too ideological or a case of political point scoring)
* Impractical (i.e. include too many aspects that should be broken into separate policies)
* Redundant (i.e. have no relevant divisions)
* Nasty (i.e. a swipe at a particular party or politician)
* Silly (i.e. clearly a joke)

*Note*: if **existing policies** are turned into problematic policies by cheeky editing, reverse the change.

Secondly, combine any **duplicate policies**.

### Priority 2: Edit at least one division

Try to do this weekly, particularly when Parliament is sitting (see the [sitting calendar](http://www.aph.gov.au/About_Parliament/Sitting_Calendar)). 

This should keep the currency of the site up just enough to keep it relevant.

### Priority 3: Advertise the policies 

Just so people know what we have - there are a lot of them!

For example: when an article appears in the media that is relevant to a policy, share it on Facebook and tweet it on Twitter along with a link to that policy (I think linking it to media will give it a bit more immediate interest).

**And then you're done!** :+1:

**Comment by MicaelaMicaela** [comment]
Sorry! Got a little trigger happy on the 'assignee' button! Feel free to take yourself off - just thought I should assign you all at the beginning so you know where to find this message.

**Comment by henare** [comment]
Cool, how about we publish this as a blog post @openaustralia/team-public-whip?

**Comment by mlandauer** [comment]
@henare @MicaelaMicaela blog post sounds like an excellent plan!

**Comment by equivalentideas** [comment]
:+1: :+1: :+1:

**Comment by MicaelaMicaela** [comment]
@henare @mlandauer  - I'm happy to make this a blog post, but I did have the Open Australia Foundation more in mind when writing this list, rather than the general public. Hopefully more people will get involved with the site but, in the meantime, I think one (or some) of you will need to take on the up-keeping role so that the site doesn't become static.

Still, I can get onto doing a blog post now if you'd like?

**Comment by equivalentideas** [comment]
I think it would even be nice to explain that it needs people in the community to take it up, but in the mean time this is what you think we should do :)

**Comment by MicaelaMicaela** [comment]
@equivalentideas - point taken! And post done! https://www.openaustraliafoundation.org.au/2015/01/30/3-ways-to-keep-they-vote-for-you-tickety-boo/

**Comment by henare** [comment]
:metal:
