### ISSUE TITLE
Blank page when you click rebellion figure link on OA

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#1053]
To reproduce:

* Visit http://www.openaustralia.org.au/senator/michael_ronaldson/victoria#votingrecord
* Click "Never rebels against their party in this parliament." [link](https://theyvoteforyou.org.au/mp.php?id=uk.org.publicwhip/member/100192#divisions) at bottom of section
* Get blank page (profile page, divisions anchor on TVFY expected)

**Comment by henare** [comment]
Seems to be Senators only. Their "More on their full record" link is missing too.

**Comment by novemberkilo** [comment]
@henare I think I am able to reproduce this locally - comparing what I see locally to the stack trace on production should help determine that my local is breaking for good reasons :)

Any chance of please pasting the stack trace from honeybadger? Thanks.

**Comment by novemberkilo** [comment]
Further notes following from @henare's description on how to reproduce the issue:

The "Never rebels against their party in parliament" link is: 

      https://theyvoteforyou.org.au/mp.php?id=uk.org.publicwhip/member/100192#divisions

This does not load, neither does (swap `member` for `senator`): 

      https://theyvoteforyou.org.au/mp.php?id=uk.org.publicwhip/senator/100192#divisions

But swapping `member` for `lord` does (although it does not appear to anchor at #divisions): 

     https://theyvoteforyou.org.au/mp.php?id=uk.org.publicwhip/lord/100192#divisions

**Comment by henare** [comment]
>Any chance of please pasting the stack trace from honeybadger? Thanks.

@novemberkilo there's no stacktrace, it 404s.

**Comment by novemberkilo** [comment]
So based on what I see thus far, the issue is that the link is being incorrectly generated for senators. The link currently has an `id` parameter that looks like `uk.org.publicwhip/member/100192` but for senators it should be `uk.org.publicwhip/lord/100192`

Does this sound right @henare?

**Comment by henare** [comment]
>Oh right ... see I thought it would be a 500 because I'm erroring out locally with something like:
>
> Division#aye_majority delegated to division_info.aye_majority, but division_info is nil
>
>Which might be about my local db still being incomplete? 

D'oh! Yeah you need to [build the caches](https://github.com/openaustralia/publicwhip/#australia-1) (eugh!). Run this and you should be hunky dory:

    rake application:cache:all_except_member_distances

If you have ideas about tidying up the doco so this is clearer for other developers that would be fantastic :musical_note: 

>Anyway, based on what I see thus far, the issue is that the link is being incorrectly generated for senators. The link currently has an id parameter that looks like uk.org.publicwhip/member/100192 but for senators it should be uk.org.publicwhip/lord/100192
>
>@henare WDYT? (As you can see I'm having trouble determining whether I am correctly reproducing the bug locally or not)

That sounds about right. However I'd like to see if we can fix it TVFY side rather than OA's side, i.e. not regenerate those links but just make the "broken" ones work.

If those numeric ID parts (e.g. 100192) are unique then we should be able to do that and we'll be golden.

**Comment by novemberkilo** [comment]
@henare: thanks for the tip regarding the cache. As you can see I've made some progress. The "divisions anchor" bit is problematic because if I am not mistaken, there is no element with `id = divisions` on the page.

**Comment by henare** [comment]
>thanks for the tip regarding the cache. As you can see I've made some progress.

:tada: 

>The "divisions anchor" bit is problematic because if I am not mistaken, there is no element with id = divisions on the page.

Does it do anything on the Representatives pages then? If not, then it's not an issue, right?

You could probably even compare it to publicwhip.co.uk and work out what what we changed :sparkles:

**Comment by novemberkilo** [comment]
> Does it do anything on the Representatives pages then? If not, then it's not an issue, right?

> You could probably even compare it to publicwhip.co.uk and work out what what we changed :sparkles:

1. There doesn’t appear to be such an anchor for representatives
2. This is what happens for publicwhip.org.uk — http://www.publicwhip.org.uk/mp.php?mpn=Diane_Abbott&mpc=Hackney_North_and_Stoke_Newington&house=commons#divisions

So … is there nothing to do here (because we seem to have done away with a #divisions anchor)?

**Comment by henare** [comment]
>So … is there nothing to do here

Seems like it to me. Not having the anchor seems like a separate issue since it already affects the Representatives links (which aren't part of this issue).

**Comment by novemberkilo** [comment]
Ok cool - I've cleaned up the PR ...

**Comment by henare** [comment]
Nice!

If you say "Fixes #1053" in your PR these close automagically :smile:
