### ISSUE TITLE
Remove tests that compare pages with old PHP app

### ISSUE THREAD

**Issue by keithpitty** [openaustralia/publicwhip#1055]
@henare Do these tests still serve a purpose?

I'm presuming we need to introduce more unit tests before we're happy to remove all the specs in `spec/requests`.

**Comment by keithpitty** [comment]
Note: after forking the repo and setting up the app, the only specs that failed were some within `spec/requests`. My gut feeling is that it would be best to introduce more unit tests rather than maintaining these "comparison with old app pages" tests. But I'm new to the codebase so would appreciate other viewpoints before I dive in too much further.

**Comment by henare** [comment]
Hey @keithpitty, yes that's exactly where we want to go :+1: We want to remove the page comparison tests and replace them with appropriate unit and integration tests.

**Comment by henare** [comment]
This has been really well written up on #1144 so I'll close this as a duplicate.
