### ISSUE TITLE
NoMethodError - undefined method `downcase&#39; for nil:NilClass

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#1064]
https://theyvoteforyou.org.au/mp.php?house=representatives
## Backtrace

```
line 34 of [PROJECT_ROOT]/config/routes.rb: block (2 levels) in <top (required)>
```

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/37542/faults/13774839)

**Comment by Tanuja-Sawant** [comment]
Is this still a valid issue? Shall I work on it? @henare

**Comment by Tanuja-Sawant** [comment]
How do I reproduce this error?

**Comment by equivalentideas** [comment]
>  If my next step has to be reproducing this error, how do I do that?

Navigate here http://localhost:3000/mp.php?house=representatives

Then you'll get the full backtrace etc.

**Comment by Tanuja-Sawant** [comment]
@equivalentideas Thanks for the tip! I've submitted a PR. Please review.
