### ISSUE TITLE
"summarising divisions" link under "You can help" should go somewhere that describes the process

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#1067]
It currently goes to the divisions list which isn't very helpful.

**Comment by equivalentideas** [comment]
:+1:

**Comment by essymo** [comment]
Hi @henare I can work on this.
Maybe if the link "summarising divisions" can take the user to the [research] ((https://theyvoteforyou.org.au/help/research/)) || [Style guide](https://theyvoteforyou.org.au/help/style-guide) will be more helpful rather than the divisions list.

**Comment by equivalentideas** [comment]
@essymo linking to the Research guide seems much more helpful 👍

**Comment by equivalentideas** [comment]
Closed by @essymo in https://github.com/openaustralia/publicwhip/pull/1140
