### ISSUE TITLE
Bronwyn Bishop appears twice on this list

### ISSUE THREAD

**Issue by SimonBiggs** [openaustralia/publicwhip#1068]
https://theyvoteforyou.org.au/people/representatives/wentworth/malcolm_turnbull/friends

Leads to he being incorrectly placed at 100%.

**Comment by henare** [comment]
Thanks for spotting this. It's something to do with the way people "change party" when they become speaker... >waves hands<

**Comment by equivalentideas** [comment]
Closing this as a duplicate of new well documented version #1082
