### ISSUE TITLE
How does someone vote 'very strongly' for something?

### ISSUE THREAD

**Issue by charliedotau** [openaustralia/publicwhip#1070]
Hey guys

A friend on Facebook just shared a screenshot of the Malcolm Turnbull page.   Someone replied asking the question "How does someone vote very strongly for something?   I looked at your FAQ, and it doesn't seem immediately apparent.

I think this might be something worth answering directly in the FAQ or somewhere.  

Love your work.
Charlie

**Comment by equivalentideas** [comment]
Hi Charlie,

Thanks for this feedback. It's helpful to know when the wording is unclear.

Click into one of the policies in an MPs voting history, for example: https://theyvoteforyou.org.au/people/representatives/wentworth/malcolm_turnbull/policies/65

The page shows the divisions that relate to the policy and how the MP voted compared to someone who supports the policy. At the bottom of the page it shows how the position is calculated. Basically, you vote very strongly for something if you vote consistently for it.

This stuff is quite complicated, and we don't think people should have to understand it all to get useful information about their MP—so we push it back. That said, I really think those MP position detail pages could be much clearer.

Can I ask, did you click into one of those pages before you raised this issue?

**Comment by charliedotau** [comment]
Hi there. Thanks for reply. I did click around - mostly through the FAQs - but I missed the page you mention.   Perhaps as you say those pages could be clearer. I'd also suggest elevating this into the FAQ.   
thanks

**Comment by equivalentideas** [comment]
>  I'd also suggest elevating this into the FAQ.

Maybe a sentence in the [“How did you decide whether someone supports a policy or not?” section](https://theyvoteforyou.org.au/help/faq#stance) about how the position strength is calculated?

Would you be up for drafting a short sentence @charliedotau ?

**Comment by henare** [comment]
Pardon the brevity but the section "*The importance of wording*" in this [mySociety post](https://www.mysociety.org/2015/08/03/how-far-does-your-mp-tread-the-party-line/) is relevant to this discussion.

**Comment by mlandauer** [comment]
I do think that this is adequately covered in the current design. There's a "what does this mean?" next to the "Voted very strongly for..." which links to a reasonable explanation.
 
![image](https://user-images.githubusercontent.com/2221/138619188-73207ba7-7196-4113-a36f-74b78e077ad5.png)

I'm not suggesting that this is perfect but it does a reasonable job and I think it's enough to close this issue
