### ISSUE TITLE
Link from openaustralia.org.au -> TVFY not working

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/publicwhip#1072]
For example on page:
http://www.openaustralia.org.au/senator/mitch_fifield/victoria

Clicking link "Hardly ever rebels against their party in this parliament."

goes to 
https://theyvoteforyou.org.au/mp.php?id=uk.org.publicwhip/member/100083#divisions

which should redirect to something else but doesn't. That makes me sad.

**Comment by henare** [comment]
Thanks for logging this @mlandauer.

>That makes me sad.

Me too.

Closing as a duplicate of #1053.

**Comment by henare** [comment]
Fixed by @novemberkilo :metal:
