### ISSUE TITLE
Error on Nick McKim's voting record

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1077]
Nick McKim's [TVFY page](https://theyvoteforyou.org.au/people/senate/tasmania/nick_mckim) currently says that he's been a senator "*since August 0015*". It also says that he has an attendance record of 3.8% (which may be correct but seems odd for the Greens senator)

**Comment by henare** [comment]
Thanks @MicaelaMicaela for spotting this rather big error! :dog: 

It's all fixed now :sparkles:

**Comment by MicaelaMicaela** [comment]
:star2:
