### ISSUE TITLE
Tried calculating agreement between senators and am getting different values to the on site ones

### ISSUE THREAD

**Issue by nickjevershed** [openaustralia/publicwhip#1083]
Hello OA friends, I wrote a script to calculate the agreement between senators based on divisions from the API (I'm working on a project looking at crossbencher voting patterns). I'm looking at all divisions since September 2013. 

[https://github.com/nickjevershed/They-vote-for-you-agreement-counter](https://github.com/nickjevershed/They-vote-for-you-agreement-counter)

However, my results don't match with the results displayed on site, eg. Glenn Lazarus [here](https://theyvoteforyou.org.au/people/senate/queensland/glenn_lazarus/friends) has an agreement of 74% with Nick Xenophon. My calculation puts their agreement at 69%.

To double check if I'd messed something up with the agreement calculation, I did a simpler calculation for only the two senators [here](https://gist.github.com/nickjevershed/b45af56fcaa6b26ab827) and am still getting 69%.
- Have I missed some division, perhaps I've messed up something with the way divisions should be obtained via the API? 
- How are the person to person agreement scores calculated on they vote for you, and are the calculations weighted in some way, or is it a straight (number of votes where both agree / number of votes both present at) ?

**Comment by henare** [comment]
>How are the person to person agreement scores calculated on they vote for you, and are the calculations weighted in some way, or is it a straight (number of votes where both agree / number of votes both present at) ?

All the logic is in the [`MemberDistance` model](https://github.com/openaustralia/publicwhip/blob/master/app/models/member_distance.rb) but [the tests](https://github.com/openaustralia/publicwhip/blob/master/spec/models/member_distance_spec.rb) might be a better place to look to understand how it _should_ work. It looks very complex and therefore bug-prone :bug:

**Comment by nickjevershed** [comment]
Thanks, I'll have a look through and try to wrap my head around it :)

**Comment by mlandauer** [comment]
I'm going to assume that looking at the code made it all make sense ;-)
