### ISSUE TITLE
Policy page improvements

### ISSUE THREAD

**Issue by brtrx** [openaustralia/publicwhip#1088]
I've mocked up some UX-driven improvements to the Policy Page, using this page as a template:
https://theyvoteforyou.org.au/policies/47 

The design below is based on the following user stories.

As a visitor to this page, I want to:

- quickly understand the level of support or opposition to this policy
- be able to find out how a particular member voted (usually my local member), even if I don't know they're face, or even their name
- use this page to familiarise myself with the allies / opponents of a particular policy

My first impression was that scanning this page effectively required being familiar with the faces of most members of parliament, which is surely an onerous requirement. The other user stories kind of followed from there. Hopefully, the stories make it clear why I've added these features:

- a support summary, showing the number of members in each grouping, with a bar graph as a visual representation to provide a sense of overall support for/against
- anchor links in this summary, so an advanced user can jump to the grouping of interest
- a live text filter, based on member name or electorate

![option 2c option 1 overview iteration 2](https://cloud.githubusercontent.com/assets/8436356/13811352/6d03bc62-eb75-11e5-9ea9-e869fc4fe4fd.png)

# Notes
## Behaviour of the text filter:

1.  I won't prescribe a min number of chars (though less is better)
2.  Groupings that are empty after filtering should be hidden
3.  Filter should match based on first name or last name or electorate, and can be set to match from start of word (rather than anywhere within these fields) if performance requires

## Responsive notes

- At small screen widths, bars can be wrapped underneath the relevant anchor link, but are ultimately optional if this doesn't work
- Text filter should wrap underneath grouping logic ("Grouped by agreement score, based on 4 relevant divisions")

**Comment by equivalentideas** [comment]
Thanks @brtrx there's lots of interesting ideas here, in particular I've always been wanting some way to help the many people who wont recognise an mp :smile:

I think you've got too many proposed changes in one issue though. It makes it much harder to discuss and track the process. Could you please open new issues relating to each change you're suggesting?

**Comment by brtrx** [comment]
Fair enough. I've divided this up into:

- Adding names to the list (#1090)
- Add live text filter (#1091)
- Add a summary of groupings (#1093)

Closing this issue.

**Comment by equivalentideas** [comment]
Nice, thanks @brtrx :tropical_drink:
