### ISSUE TITLE
Sometimes not all divisions are shown on member policy comparison page

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#1100]
If someone has moved houses then sometimes we don't show all their votes on a policy comparison page. This is because we only show the vote table for the latest member, not the person (i.e. that would include all their memberships).

You can see this in action here: https://theyvoteforyou.org.au/people/representatives/robertson/deborah_o'neill/policies/39

Deborah has voted 4 times on the policy, twice as an MP and twice as a Senator. We correctly say she voted a mixture of for and against the policy. However we only show 2 votes, which makes the whole page look wrong. We should display all 4 votes on this page.

---

[The following description was what we had before this issue was investigated]

Someone just emailed the following problems:

> The webpage for Senator Jenny McAllister (NSW) states that she "Voted very strongly against same sex marriage". However if one follows the link to "votes" at the end of this statement, one reaches a webpage indicating that she has never voted on the issue at all (most likely because she has not been in parliament for very long). Please correct the main webpage for McAllister to indicate that she has never voted on this issue, rather than claiming that she is strongly against it.
> 
> The webpage for Senator Deborah O'Neill (NSW) states that she voted a mixture of for and against increasing marine conservation. If one follows the link to "votes" at the end of this statement, one reaches a webpage indicating that no votes are listed, i.e. she has never voted on the issue at all. However, under the heading "How "voted a mixture of for and against" is worked out", it is claimed that she voted 5 times and was absent 1 time, which is inconsistent with the statement above that no votes are listed.
> 
> The webpage for Senator Deborah O'Neill (NSW) also states that she "Voted a mixture of for and against increasing restrictions on gambling". If one follows the link to "votes" at the end of this statement, one reaches a webpage indicating that she has voted in favour of increasing restrictions in both of the two divisions listed. However, under the heading "How "voted a mixture of for and against" is worked out", it is claimed that she voted with the policy 2 times and against 2 times, i.e. a total of 4 votes which is impossible as there were only 2 divisions.

**Comment by henare** [comment]
I cannot reproduce the [first issue](https://theyvoteforyou.org.au/people/senate/nsw/jenny_mcallister/policies/1):

![selection_002](https://cloud.githubusercontent.com/assets/48945/16509038/6db26306-3f7c-11e6-8cb6-ccafd692321a.png)

The [second one](https://theyvoteforyou.org.au/people/representatives/robertson/deborah_o'neill/policies/17) seems to indeed be a problem:

![selection_003](https://cloud.githubusercontent.com/assets/48945/16509042/8d501686-3f7c-11e6-8185-e50025a4f897.png)

And so does the [last one](https://theyvoteforyou.org.au/people/representatives/robertson/deborah_o'neill/policies/39):

![selection_004](https://cloud.githubusercontent.com/assets/48945/16509056/a30493c6-3f7c-11e6-86ff-30bbc1a32331.png)

**Comment by henare** [comment]
This is really weird. I'm wondering if it was related to the disk space issue, i.e. the cache refresh process may have died before it finish so the caches are out of date?

I'm running the `application:cache:policy_distances` rake task to see if that helps.

**Comment by henare** [comment]
It doesn't seem to have helped :frowning: I'm just rebuilding all the caches now. Then I guess it will be time to start poking around the data itself.

**Comment by henare** [comment]
Okay I think I know what this is. It appears isolated to Deborah O'Neill because she moved from the lower house to the upper house.

The statement about her policy position is correct but we're just not showing the votes from her other time in parliament so it looks weird. I'll update this issue.

**Comment by mlandauer** [comment]
I've noticed this bug enough times now in just browsing through the site. It definitely makes it confusing and some, given the recent press, might use this bug as an indication that there is something underhand going on which obviously there isn't but you know, perceptions and all that...

**Comment by mlandauer** [comment]
Latest version (that includes this fix) has now been deployed to production
