### ISSUE TITLE
Rails 4.1 is no longer supported

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#1104]
http://weblog.rubyonrails.org/2016/7/13/Rails-4-2-7-and-4-1-16-have-been-released/

We need to [upgrade to Rails 4.2](http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-1-to-rails-4-2).

**Comment by equivalentideas** [comment]
I'm working on this in a branch.

I've upgrade the rails gem and gems with dependency conflicts with:

> bundle update rails responders delayed_job_active_record

Now running tests.

## test failures

* [ ] change in attribute order impacts every regression test file
* [ ]   1) WikiMotion storing edit_date in local time zone should eq "2014-01-01 01:01:01"
     Failure/Error: it { expect(create(:wiki_motion, edit_date: Time.new(2014,1,1,1,1,1)).edit_date.strftime('%F %T')).to eq "2014-01-01 01:01:01" }

       expected: "2014-01-01 01:01:01"
            got: "2013-12-31 14:01:01"

       (compared using ==)
     # ./spec/models/wiki_motion_spec.rb:5:in `block (3 levels) in <top (required)>'

**Comment by equivalentideas** [comment]
Testing out my WikiMotion date fix to see if I can make some changes before upgrading and then after and all the dates work as expected. This didn't work before.

**Comment by equivalentideas** [comment]
Yay thats working ⭐ 

![screen shot 2016-08-26 at 3 03 08 pm](https://cloud.githubusercontent.com/assets/1239550/17994690/4eec5a50-6b9e-11e6-8871-621c9aa2e6af.png)

**Comment by equivalentideas** [comment]
I'm going to update the devise views to resolve the remaining deprecation warnings.

**Comment by equivalentideas** [comment]
I'm now testing out the policy calculations following these steps:

1. checkout the rails upgrade branch
2. setup a policy with 6 divisions which a range of vote positions, it includes house and senate votes.
3. run the policy `cache:all` task
4. load the policy page and keep that browser window aside
5. checkout the master branch
6. run the `cache:all` task again
7. load up the policy page in a new bowser window and compare the MP positions to the rails upgrade version of the same policy.

**Comment by equivalentideas** [comment]
[Looks like we want to be on at least rspec 3.2.1](https://github.com/rspec/rspec-rails/blob/master/Changelog.md#321--2015-02-23) too. I'll do that upgrade as well now.
