### ISSUE TITLE
Provide a csv version of the API where possible

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/publicwhip#1105]
I'm teaching a class of journalism students at the moment. While they are getting training in and becoming familiar with spreadsheets, they're far off manipulating JSON data.

Providing the [API data](https://theyvoteforyou.org.au/help/data) in CSV as well as JSON would make it much more accessible to a wider range of journalists including students. I think this applies more widely than just journos–but that's the observation I can make. I'm guessing that more people generally are familiar with spreadsheets than can work with JSON.

**Comment by henare** [comment]
Nice idea.

In the mean time there's plenty of JSON to CSV converters. I'd recommend @konklone's because he's awesome :smile: https://konklone.io/json/
