### ISSUE TITLE
mis-spelled URLs should take you to the 404 page

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/publicwhip#1116]
If you try a random generic URL we don't have a route for, it should be caught and you should get the generic 404 page. Currently it falls through the cracks and you just get a blank page. Try https://theyvoteforyou.org.au/policiis

**Comment by essymo** [comment]
Hi @equivalentideas My name is Esther I would like to take up this issue,if thats okay. Thank you

**Comment by SaumyaRawat** [comment]
Is this issue solved? If not can I take it up?

**Comment by essymo** [comment]
Hi @SaumyaRawat  Yes it was solved. Checkout some other cool 'good for first contribution' :)

**Comment by SaumyaRawat** [comment]
Okay!

**Comment by equivalentideas** [comment]
@SaumyaRawat Sorry! I forgot to update this. Also, hacker tips @essymo , if you include "Closes #1116" in the description of your PR, when it gets merged the issues gets closed automagically ✨ :D

And yep @essymo fixed this issue with https://github.com/openaustralia/publicwhip/pull/1136
