### ISSUE TITLE
Sort policy positions by confidence

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#1125]
On an MP's profile page, under each "strongly for" or "strongly against" heading, list policies by confidence level, i.e. the number of divisions each has. This means that the ones that we're more confident about are surfaced to the top of that list as they're going to be a more accurate view of the MP's voting choices.

Other ideas are to make the names darker/lighter depending on the confidence level or to add the number of votes in small text next to the policy name ("out of 24 possible votes").

**Comment by mlandauer** [comment]
Another option which I think I'm favoring right now is that we exclude particular policy positions for an MP completely if they haven't been present during a certain number of votes. Right now we do that if they've never voted. I think it would be better if we only include them if they voted yes or no on 3 or more votes. That would also make the "consistently" language make more sense more of the time

**Comment by katska** [comment]
Agree in principle but not with this threshold

**Comment by mlandauer** [comment]
> Agree in principle but not with this threshold

What threshold do you think is right @katska?

**Comment by mlandauer** [comment]
We've rolled out the change to exclude policies where a person has voted only once in a division that was not "substantive" which is making a change to the law. This change is outlined in https://www.oaf.org.au/2022/01/31/a-new-category-has-been-added-to-your-representatives-voting-records/

I think this change goes most of the way to addressing the point made in this issue without overloading the user with more information (number of divisions) where it's not super directly relevant.
