### ISSUE TITLE
Frazer Anning officially an independent as of 15 January 2018

### ISSUE THREAD

**Issue by choc96** [openaustralia/publicwhip#1172]
Senator Anning gave notice to Senate President on 15 January 2018, that he would sit as an independent. Please update his People page.

Sources: https://www.sbs.com.au/news/senator-confirms-split-with-one-nation
http://www.abc.net.au/news/2017-11-13/hanson-says-anning-has-abandoned-one-nation/9144142

**Comment by MicaelaMicaela** [comment]
Thanks! I've [made a pull request](https://github.com/openaustralia/openaustralia-parser/pull/33) with this change
