### ISSUE TITLE
Dean Smith is not a rebel - CORRECTION NEEDED

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1176]
We have a serious problem in our data that I need help to solve.

A new Labor D Smith (David Smith) has entered the Senate and is being mixed up with the existing Liberal D Smith (Dean Smith) which is very bad because they are in different parties and the Liberal Senator now looks like a rebel (with 23 falsely listed rebel votes in the past week alone)

To solve this issue we need to:

**1) Update our data**
I have created pull requests to add David Smith to [our people list](https://github.com/openaustralia/openaustralia-parser/pull/42) and to [our senators list](https://github.com/openaustralia/openaustralia-parser/pull/43). Note that in our people list, I also added Dean Smith's middle name to lessen the likelihood of the two getting mixed up again.

**2) Re-upload the affected divisions**
So far, only the following **Senate** sitting days need to be re-uploaded:
18 Jun 2018
19 Jun 2018
20 Jun 2018
21 Jun 2018

25 Jun 2018
26 Jun 2018
27 Jun 2018
28 Jun 2018

Though until this issue is sorted, more sitting days will be affected.

Thank you, your help is much appreciated!!

**Comment by jamezpolley** [comment]
We've pushed updates to OA and TVFY today that have fixed most of this.  https://theyvoteforyou.org.au/people/senate/wa/dean_smith is now showing a much lower rebellion score, for instance, and speeches on OA are correctly attributed to David Smith.

We're waiting for the cache updates to complete, which will probably take a few hours. This should be fully reflected on TVFY and OA tomorrow (or perhaps the day after, depending on just how long the updates take)

**Comment by jamezpolley** [comment]
https://theyvoteforyou.org.au/people/senate/act/david_smith now has David Smith's voting record
https://theyvoteforyou.org.au/people/senate/wa/dean_smith no longer has David Smith's votes recorded.
https://www.openaustralia.org.au/senator/david_smith/act now shows speeches for David Smith.

@MicaelaMicaela Thanks for your help, as always :)
