### ISSUE TITLE
provide single summary page for how 'voted ((very )?strongly|moderately)? (for|against)' is derived ...

### ISSUE THREAD

**Issue by mjcherbert** [openaustralia/publicwhip#1179]
my first exposure to this site was via a non-attributed screen grab of Scott Morrison's voting record on FaceBook.  I found this site after some hunting, but would have liked to have thrown a link back to the thread not only for the site landing page but also somewhere where the content of the image could be explained better - a single page that outlines how the derivation for each of the 'voted very strongly', 'voted strongly', etc metrics were calculated.  It is present on individual representative pages, but doesn't appear to be tied together in a way that allows for easy follow-up to the static screengrab (did I mention I hate non-attributed screengrabs?)

Requires #1180

**Comment by katska** [comment]
Hi
You mentioned it you hate that - there's a share button at https://theyvoteforyou.org.au/people/representatives/cook/scott_morrison which would link back - 
- currently that share doesn't show you the info you may want to share - so it could be better to be able to highlight some specific things? Do you have a suggestion about that? 
I've even just done the same thing myself on twitter, which I'm of course mildly embarrassed about. Thanks for calling it out.
Also in response to how 'strongly' 'very strongly' are worked out, it's definitely a challenge to keep things clear and provide information in context in a way that is specifically helpful. IF you think it's buried and have suggestions for improving then please add a seperate issue for that. 
Thanks again @mjcherbert

**Comment by jamezpolley** [comment]
> You mentioned it you hate that - there's a share button at https://theyvoteforyou.org.au/people/representatives/cook/scott_morrison which would link back 

I've seen a lot of tweets/FB posts over the last few days, some sharing a screenshot that I assume is the same one @mjcherbert saw, and others that used the share button.

The difference has been that the screenshot has a big list, right there, visible in the tweet/facebook post. People can comment on it immediately and start discussing it.

The tweets/posts using the share button just say something generic about being able to view the voting record and provide a link. People would have to click the link to see the voting record before they can comment.

I do agree that unattributed screenshots are pants; but I think they're doing something that the share button can't do.

I'm not sure how to change the share button; but I can think of ways to make TVFY and OA more screenshot-friendly.

All the screenshots I've seen been from OA and have had something at the top about "this data is from they vote for you" - that doesn't work as a link in the image, but does let people use a search engine to find the site.

**Comment by jamezpolley** [comment]
Idle thought: I wonder if we could put enough data in OpenGraph metadata to make those a useful way to share things?

**Comment by mjcherbert** [comment]
On Sun, Aug 26, 2018 at 05:38:55PM -0700, James Polley wrote:
|The difference has been that the screenshot has a big list, right
|there, visible in the tweet/facebook post. People can comment on it
|immediately and start discussing it.

yes, I think that's the main take-away: the list is useful because it
immediately shows a trend on a wide range of issues over time. Obviously
a screengrab isn't interactive, but if there were an explanatory page
that could be posted in a follow-up, that would help to draw people back
to the source

Regards,
Malcolm

-- 
Malcolm Herbert
mjch@mjch.net

**Comment by jamezpolley** [comment]
This is related to #1180 - but it's not identical, so I'm not going to close it.

**Comment by mlandauer** [comment]
Closing this issue in favor of #1316 which will be adding easy screenshots when sharing via social media which will have correct attribution so people can follow the links and understand what it all means
