### ISSUE TITLE
Division wrongly marked as "passed"

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1185]
In [this division](https://theyvoteforyou.org.au/divisions/representatives/2018-09-17/1), we have wrongly recorded the Speaker Tony Smith as casting his vote with the ayes, when in fact he cast it with the noes in line with the normal parliamentary rules (where a vote on an amendment is tied, the speaker must cast their vote to leave the bill unchanged as the onus is on those that want the change)

I've confirmed this with Hansard, [which stated](https://www.aph.gov.au/Parliamentary_Business/Hansard/Hansard_Display?bid=chamber/hansardr/b8101fb1-edde-4753-a50e-1709934db485/&sid=0000):
> The House divided. [12:37]
> (The Speaker—Hon. Tony Smith)
>
> The numbers for the ayes and the noes being equal, the Speaker gave his casting vote with the noes.
> Question negatived.

**Comment by jamezpolley** [comment]
https://www.openaustralia.org.au/debates/?id=2018-09-17.26.2

> I think this part of the day is a bad time to get thrown out, Member for Fenner. As I've said before in these circumstances House of Representatives Practice outlines the principles that have been used in the exercise of the casting vote, one of which is that a casting vote on an amendment should leave a bill in its existing form. This principle has seen the casting vote used against amendments, therefore I cast my vote with the noes.

**Comment by jamezpolley** [comment]
I believe this can be traced back to this:

https://github.com/openaustralia/openaustralia-parser/blob/acf55857dba673ff55817cb177b36e51712f516a/lib/hansard_division.rb#L28

```
  def passed?
    case @content.at('(division.result)').inner_text
    when /agreed to/
      true
    when /negatived/
      false
    when /was not carried/
      false
    else
      raise 'Could not determine division result'
    end
  end
```

IE, we look first for the words "agreed to"; if found, the motion is considered to have passed. Then we look for "negatived"; if found, the motion failed. Then we look for "was not carried"; if found, the motion failed.

In this case, the Hansard says:

` <p class="HPS-DivisionFooter">The numbers for the ayes and the noes being equal, the Speaker gave his casting vote with the noes.<br />Question negatived.<br />Original question agreed to.</p>`

We match on "Agreed to" first so this is flagged as a yes.

The only solution I can think of here is to look for "casting vote with the noes" first

**Comment by jamezpolley** [comment]
Cache updated, vote counts show correctly.
