### ISSUE TITLE
October divisions missing

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1186]
Only one October division - on the 24th - has appeared on TVFY. We're missing two sitting weeks' worth (15-18 Oct + 22-26 Oct). I though this might be connected with [this OA issue](https://github.com/openaustralia/openaustralia/issues/652), but seems not.

Cheers!

**Comment by jamezpolley** [comment]
It looks like this just need some poking to make it load the divisions from OA after we got OA fixed.

I've run ```RAILS_ENV=production bundle exec rake application:load:divisions[2018-09-10,2018-10-26] to load in all the data from OA, and then  ```RAILS_ENV=production bundle exec rake application:cache:all_except_member_distances``` to update the caches. 

I'm now seeing the divisions page loading with all the divisions from this month. Policy distance cache is still being updated, and I'm going to leave member distances for the regular cronjob
