### ISSUE TITLE
Need to edit people_csv_reader.rb to recognise UAP

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1188]
The United Australia Party (UAP) is back. Formerly, it was the Palmer United Party (PUP) so we need to edit [people_csv_reader.rb](https://github.com/openaustralia/openaustralia-parser/blob/b4d0eb16072ded4a163040c93e1d032f70d59f1a/lib/people_csv_reader.rb) file with:

> when "UAP"
> "United Australia Party"

(I can't make the edit myself as I'm not on a branch.)

**Comment by MicaelaMicaela** [comment]
Should add - once this file updated and UAP recognised in our system, we need to update Senator Brian Burston's information - on 18 Jun 2018 he actually moved from PHON (Hanson's party) to UAP, as confirmed by the following ABC News articles (note his [APH entry](https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=207807) doesn't have dates listed for the change - I swear the Parl House website folks are as sick as we are of having to update every time an MP or Sen changes party, which seems to be every few days...):

* Quits P Hanson: https://www.abc.net.au/news/2018-06-14/one-nation-senator-brian-burston-quits-after-pauline-hanson-feud/9868226
* Enters C Palmer Party: https://www.abc.net.au/news/2018-06-18/brian-burston-will-run-for-clive-palmers-party-next-election/9879984

**Comment by jamezpolley** [comment]
Have done both of these. OA has been updated, TVFY caches are being updated. https://theyvoteforyou.org.au/people/senate/nsw/brian_burston still hasn't quite caught up but will by tomorrow, so I'm closing this.
