### ISSUE TITLE
Bill mislabeled in division

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1193]
This [division](https://theyvoteforyou.org.au/divisions/senate/2018-10-18/5) says it's related to the Treasury Laws Amendment (Lower Taxes for Small and Medium Businesses) Bill 2018 when it's actually the [third reading division](https://www.openaustralia.org.au/senate/?id=2018-10-18.83.1) for the Government Procurement (Judicial Review) Bill 2017.

**Comment by jamezpolley** [comment]
I ran the "load divisions" tasks mentioned at https://github.com/openaustralia/publicwhip#australia-1 and this updated the links. The links on TVFY now go to the correct debate on OA.
