### ISSUE TITLE
Can't edit divisions on TVFY

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1200]
It happened again! Like with issue #1187, although I can write new division summaries, they won't save. I simply return to the unedited division page.

**Comment by jamezpolley** [comment]
Once again, `systemctl restart elasticsearch.service` got this up and running again.

newrelic monitoring did notice the elasticsearch process going away, and the timestamp seems to roughly correspond with updating SSL certificates (which requires shutting down apache and restarting it). Seems like we should probably restart elasticsearch when we update the certificates.
