### ISSUE TITLE
[They Vote For You/production] ActionView::Template::Error: Division#aye_majority delegated to division_info.aye_majority, but division_info is nil: #<Division id: 5762, valid: true, date: "2019-07-22", number: 7, house: "senate", name: "Business &#8212; Rearrangement", source_url: "http://parlinfo.aph.gov.au/parlInfo/search/display...", debate_url: "http://parlinfo.aph.gov.au/parlInfo/search/display...", motion: "<p class=\"speaker\">Penny Wong</p>\n\n<p>I understand...", clock_time: "021:02:00", source...

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#1204]
## Backtrace

    line 11 of [PROJECT_ROOT]/app/models/division.rb: rescue in aye_majority
    line 11 of [PROJECT_ROOT]/app/models/division.rb: aye_majority
    line 71 of [PROJECT_ROOT]/app/models/division.rb: tied?

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/37542/faults/33534926)

**Comment by jamezpolley** [comment]
https://theyvoteforyou.org.au/divisions/senate/2019-07-22/7

This seems to be a one-off; I can't reproduce it on either https://theyvoteforyou.org.au/people/senate/nsw/concetta_fierravanti-wells or https://theyvoteforyou.org.au/divisions/senate/2019-07-22/7

The timing seems to be around the time we'd be doing the daily update, so it may have just been a page view that happened just as this division was being updated.
