### ISSUE TITLE
Division with wrong voting data @ 5:28pm 23 Jul 2019

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1205]
At 5:28pm on 23 July 2019 there was a second reading division with 106 ayes (101 majority) and 5 noes - I have confirmed this on Hansard.

On TVFY, the [5:28pm division](https://theyvoteforyou.org.au/divisions/representatives/2019-07-23/1) currently reads as not passed with 71 ayes and 76 noes. These results are wrong and seem to have been copied from the following [6:09pm division](https://theyvoteforyou.org.au/divisions/representatives/2019-07-23/2), which appears on TVFY accurately.

**Comment by jamezpolley** [comment]
* Confirmed that the error is visible in the XML file on OpenAustralia
* `rm -rf /srv/www/production/shared/html_cache/2019-07-23` to remove the downloaded/cached data from that day
* `./parse-speeches --force 2019-07-23` to re-read the updated hansard from the website
* xml file now has the right data.

**Comment by jamezpolley** [comment]
````bash
deploy@ip-172-31-37-36:/srv/www/production/current$ RAILS_ENV=production bundle exec rake application:load:divisions[2019-07-23]
Saving division: representatives 2019-07-23 1
Saving division: representatives 2019-07-23 2
Truncating very long motion text for division: representatives 2019-07-23 2
Saving division: representatives 2019-07-23 3
Truncating very long motion text for division: representatives 2019-07-23 3
Saving division: senate 2019-07-23 1
Saving division: senate 2019-07-23 2
Saving division: senate 2019-07-23 3
deploy@ip-172-31-37-36:/srv/www/production/current$ RAILS_ENV=production bundle exec rake application:cache:division
Updating cache of guessed whips...


Updating division cache...
````

https://theyvoteforyou.org.au/divisions/representatives/2019-07-23/1 now has the right data.
