### ISSUE TITLE
Andrew Wilkie is listed incorrectly in a no longer existing electorate.

### ISSUE THREAD

**Issue by SlyPhi** [openaustralia/publicwhip#1207]

**Comment by jamezpolley** [comment]
https://www.openaustralia.org.au/mp/andrew_wilkie/clark seems to be correct; https://theyvoteforyou.org.au/people/representatives/denison/andrew_wilkie is wrong (denison is the no-longer-existing electorate)

**Comment by mlandauer** [comment]
Now urls for "old" memberships get redirected to the most recent member. So, this is now fixed
