### ISSUE TITLE
Incorrect information in House divisions 22 July 2019

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1209]
I can't place two House of Reps divisions from 22 July 2019

The [first](https://theyvoteforyou.org.au/divisions/representatives/2019-07-22/5) is listed on TVFY as taking place at 5:38pm. While there was a division at this time according to Hansard, the results are different: Hansard calls it Noes 76, Ayes 65 while we say it was Ayes 78, Noes 67.

The [second](https://theyvoteforyou.org.au/divisions/representatives/2019-07-22/6) is listed at 5:45pm, but Hansard records no vote at that time.

**Comment by jamezpolley** [comment]
> The first is listed on TVFY as taking place at 5:38pm. While there was a division at this time according to Hansard, the results are different: Hansard calls it Noes 76, Ayes 65 while we say it was Ayes 78, Noes 67.

The vote at 17:38 seems to be correct to me. I'm looking at https://parlinfo.aph.gov.au/parlInfo/download/chamber/hansardr/094f9d89-b5ce-43ef-8ad4-277117167c00/toc_pdf/House%20of%20Representatives_2019_07_22_7073_Official.pdf;fileType=application%2Fpdf page 139

https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;adv=yes;db=CHAMBER;id=chamber%2Fhansardr%2F094f9d89-b5ce-43ef-8ad4-277117167c00%2F0167;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Date%3A22%2F7%2F2019;rec=0;resCount=Default has the same

> The SPEAKER: The question is that the motion be put.
> The House divided. [17:38]
> (The Speaker—Hon. Tony Smith)
> Ayes ......................78
> Noes ......................67
> Majority.................11

Am I looking at the wrong thing?

**Comment by jamezpolley** [comment]
I'm seeing a division at 17:45 - https://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;adv=yes;db=CHAMBER;id=chamber%2Fhansardr%2F094f9d89-b5ce-43ef-8ad4-277117167c00%2F0168;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Date%3A22%2F7%2F2019;rec=0;resCount=Default

**Comment by MicaelaMicaela** [comment]
No, no, you're completely right @jamezpolley . I've just gone back into Hansard and, like you said, the TVFY divisions check out fine. I have no idea what I was looking at when I made this issue... Was I looking at the wrong day that coincidentally had a division of the same nature at 17:38? Maybe!

Sorry for sending you on a wild goose chase. I'll close this now.
