### ISSUE TITLE
Senate divisions missing for 14-17 Oct 2019 on TVFY

### ISSUE THREAD

**Issue by MicaelaMicaela** [openaustralia/publicwhip#1210]
There are currently no [divisions](https://theyvoteforyou.org.au/divisions) from the Senate showing up on TVFY for the 14-17 Oct 2019 sitting week, though divisions did take place.

**Comment by jamezpolley** [comment]
````./lib/hansard_parser.rb:190:in `throw': uncaught throw `2019-10-17 senate: Couldn't figure out who Henderson, SM is in division (voting yes)' (NameError) ````

**Comment by jamezpolley** [comment]
@MicaelaMicaela Looks like we have some data updates we need.

https://www.aph.gov.au/Senators_and_Members/Parliamentarian?MPID=ZN4

> Elected to the House of Representatives for Corangamite, Victoria, 2013. Re-elected 2016. Defeated at the general election, 2019. Chosen by the Parliament of Victoria 11.9.2019 under section 15 of the Constitution to represent that state in the Senate, vice M Fifield (resigned).

**Comment by MicaelaMicaela** [comment]
Thanks for seeing this @jamezpolley ! I'm set to do TVFY work on Thursday this week and can make this change then.

**Comment by MicaelaMicaela** [comment]
On second thought, I'll do it now @jamezpolley - always best to get these things done asap and I'm stopping my other work for lunch anyway.

**Comment by MicaelaMicaela** [comment]
Done: https://github.com/openaustralia/openaustralia-parser/pull/83
