### ISSUE TITLE
Missing divisions - sitting week 25-28 November 2019

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/publicwhip#1216]
TVFY is currently missing House of Reps divisions for 27 November 2019 and all Senate divisions for this sitting week (25-28 November 2019).

We may be missing the Senate divisions due to a senator leaving (see [pull request](https://github.com/openaustralia/openaustralia-parser/pull/89)) but I'm not sure why we're missing the House divisions for that one day - unless anyone's aware of an MP leaving too?

**Comment by jamezpolley** [comment]
We've not got all the debates loaded into OAF.

Adding Jim Molan made some progress. But in addition, the 27th took an abormally long time to process for reasons I haven't been able to figure out.
