### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by naverone** [openaustralia/publicwhip#1222]
Trying to use your API through They Vote for You but keep falling foul of CORS - is there any chance you could change your CORS headers to open the API up?

**Comment by mlandauer** [comment]
Ah yes of course. I can't remember off the top of my head what we did with CORS on the TheyVoteForYou API.

I can take a look at this later today and remind myself about the setup. Of course if you have some time right now a PR would be very gladly accepted! :-)

**Comment by mlandauer** [comment]
That's now deployed to production. And the following quick test shows that it's working. The output of 
```
curl -H "Origin: http://foo.com" -I https://theyvoteforyou.org.au
```
now includes the following two lines:
```
access-control-allow-origin: *
access-control-allow-methods: GET
```

**Comment by mlandauer** [comment]
@naverone please let me know if that fixes the problems you've had!

**Comment by naverone** [comment]
Thank you! That seems to have fixed everything and my page is now loading so much faster than it was when I was working around the issue. Appreciate your help.

**Comment by mlandauer** [comment]
@naverone great to hear. I would love to see what you're doing with the API if and when you're ready to share.

**Comment by naverone** [comment]
Thanks - would like to chat through what I'm doing, especially as I don't wan to hit your server too much. Can we get in touch directly?
