### ISSUE TITLE
Update representative profile pictures

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/publicwhip#1225]
We've had a request via Facebook for updated profile pictures for our MPs/senators. We are currently using older photos that are no longer in use on the [aph.gov.au](https://www.aph.gov.au/Senators_and_Members) website. We are also missing photos for the more recent MPs/senators

**Comment by katska** [comment]
Thanks @mackaymackay Good point yes!

**Comment by mlandauer** [comment]
As part of fixing #1351 and #1276 the images should now have all been updated
