### ISSUE TITLE
Log in/Sign up functions not working

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/publicwhip#1239]
I am currently not able to log in to my TVFY account (after typing in my password, it goes to a blank screen). We also received an email earlier this week (28 Aug) from a user who tried to sign up for an account and also hit a blank screen after typing in their details.

**Comment by mlandauer** [comment]
@mackaymackay as I mentioned on Slack this is most likely caused by the recent ruby and app updates I did. This is the first thing I'm working on fixing this morning. Sorry I couldn't fix it immediately on Friday
