### ISSUE TITLE
New divisions not appearing on TVFY (11-12 May)

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/publicwhip#1241]
This week's divisions are not being uploaded onto TVFY. I have checked to see if there have been any new MP/Senator appointments (as that has caused this issue in the past), but have not found any.

**Comment by mlandauer** [comment]
Deployed this fix and running `rake application:load:daily` by hand. I expect it won't load everything from last week....

**Comment by mlandauer** [comment]
Ran `RAILS_ENV=production bundle exec rake application:load:divisions[2021-04-01,2021-05-19]` followed by `RAILS_ENV=production bundle exec rake application:cache:all`

**Comment by mlandauer** [comment]
The divisions from last week have now all loaded. It's still recalculating the caches but I have no reason to believe there should be any problems with that
