### ISSUE TITLE
Make draft policies show their 'draft' status

### ISSUE THREAD

**Issue by katska** [openaustralia/publicwhip#1250]
Someone posted on twitter, mis-representing a draft policy externally edited, as a reasonable reflection of someone's voting record. Partly they were able to do this because draft policies don't look different to other policies.  

https://twitter.com/thesayno7/status/1441072749447761927

SN7 🌱SN7 🌱 @thesayno7
Age Pensioners are already on the #cashlessdebitcard in one site. The payment entered the CDC legislation for the first time as a "restrictable payment" in Dec 2020. Limits to wider OAP inclusion rest on 1 line of text subject to instrument.
Src: https://theyvoteforyou.org.au/people/senate/sa/anne_ruston/policies/266
#auspol 

Make it clear then that a draft policy is a DRAFT, a work in progress, and as such might not be anything like an accurate representation of the voting record.

**Comment by mlandauer** [comment]
Fixed by ba335d2dbfe111a24178f95d549cbdf848336c8b and ff0a4a251a37126f5f21cb2f7a0c55e1aeb514bd
