### ISSUE TITLE
links to policies/votes from openaustralia no longer work

### ISSUE THREAD

**Issue by katska** [openaustralia/publicwhip#1265]
If I look at [Justine Elliot's profile at openaustralia.org.au ](https://www.openaustralia.org.au/mp/justine_elliot/richmond) and click on the [first policy](https://theyvoteforyou.org.au/mp.php?mpid=160&dmp=1) - it returns ['sorry page not found'](url)

even tho there is a policy on this https://theyvoteforyou.org.au/people/representatives/richmond/justine_elliot/policies/1 (the title is shown as same sex marriage rather than same sex marriage equality)
For example on [same sex marriage equality](https://theyvoteforyou.org.au/people/representatives/richmond/justine_elliot/policies/1)

I've tried a few others with the same result.

**Comment by mlandauer** [comment]
Yikes I think this is because I cleared out a bunch of old php routes that I thought weren't being used anymore but it looks like it's being used here. I'll fix this immediately.
