### ISSUE TITLE
Generate twitter card as part of twitter share button from the MP's policy page

### ISSUE THREAD

**Issue by xavella** [openaustralia/publicwhip#1277]
As a user, when I click the share button on the MP's policy page, I want the content I'm sharing to appear in the post as opposed to just a hyperlink back to the page, as my intention is to share the content as opposed to a nondescript hyperlink. 

Preferred implementation:  render an image containing the content and when clicking 'share' pull that image into a twitter card inserting both the image and a hyperlink in the tweet. People are achieving a similar outcome by taking a screen shot of the policy page, but the formatting and aspect ratio is all wrong for the twitter platform. Also helpful to use a url shortener

Example implementation:  
![image](https://user-images.githubusercontent.com/15383553/140584258-d884f208-9a9d-404a-8f1d-ebc5deca8153.png)
https://theyvoteforyou.org.au/people/representatives/mackellar/jason_falinski/policies/166 via @TheyVote4You 

Currently implementation: 
https://theyvoteforyou.org.au/people/representatives/mackellar/jason_falinski/policies/166 via @TheyVote4You 

Note, this functionality is already present when clicking the twitter share from the MP's page: 
https://theyvoteforyou.org.au/people/representatives/mackellar/jason_falinski

**Comment by mlandauer** [comment]
Good call. Since we already do this for an MPs page it makes sense to do it for a policy page which is what someone would share if they were talking about how a particular MP votes on a particular issue.
