### ISSUE TITLE
Division should say "not passed" as absolute majority req'd

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/publicwhip#1286]
This following division should be marked as "not passed" as it did not achieve absolute majority, as required in this case: https://theyvoteforyou.org.au/divisions/representatives/2021-11-25/2

**Comment by mlandauer** [comment]
Is this a duplicate of #473?

**Comment by mlandauer** [comment]
I'm closing this in favour of #473 which is the more general issue
