### ISSUE TITLE
help/faq: a number of external links are broken

### ISSUE THREAD

**Issue by bobsbarrels** [openaustralia/publicwhip#1289]
There are links to external webpages that no longer exist:

This is the list found so far, just eyeballing "faq", though there may be more.

---

https://theyvoteforyou.org.au/help/faq#division-occur

Most decisions in Parliament are made **‘on the voices’** and not by division. 

broken: https://peo.gov.au/understand-our-parliament/voting-in-the-chambers.html

---

https://theyvoteforyou.org.au/help/faq#rebel

voting against the **party whip**. 

broken: https://peo.gov.au/understand-our-parliament/party-whip.html

---

https://theyvoteforyou.org.au/help/faq#attendance

Link from **pair** is broken:

broken:  https://www.aph.gov.au/Help/404?item=%2fabout_parliament%2fsenate%2fpowers_practice_n_procedures%2fodgers%2fchap1107&user=extranet%5cAnonymous&site=website

![Screenshot from 2021-12-01 07-44-31](https://user-images.githubusercontent.com/26145487/144125205-71d3f6cd-76ed-4152-a286-5d32c05b0c5b.png)

---

https://theyvoteforyou.org.au/help/faq#tied-division

tied it is **considered to have failed** because

broken: https://peo.gov.au/understand-our-parliament/voting-in-the-chambers.html

**Comment by bobsbarrels** [comment]
If correct link is provided I'm happy to fix this :)

**Comment by bobsbarrels** [comment]
Actually this is the tip of an iceberg. Collecting bunch of broken external links ... TBA.

**Comment by katska** [comment]
The information is now at https://www.aph.gov.au/About_Parliament/Senate/Powers_practice_n_procedures/Odgers_Australian_Senate_Practice/Chapter_11 although not in a usefully separate section as before http://web.archive.org/web/20170403002105/http://www.aph.gov.au/About_Parliament/Senate/Powers_practice_n_procedures/odgers/chap1107

**Comment by bobsbarrels** [comment]
> The information is now at https://www.aph.gov.au/About_Parliament/Senate/Powers_practice_n_procedures/Odgers_Australian_Senate_Practice/Chapter_11 although not in a usefully separate section as before http://web.archive.org/web/20170403002105/http://www.aph.gov.au/About_Parliament/Senate/Powers_practice_n_procedures/odgers/chap1107

Looks like PEO have done an upgrade also, but it's not totally stable. Some googling around gave me this link for "on the voice", though it timed out then came up with a server error then loaded as I think the correct page:
https://peo.gov.au/understand-our-parliament/how-parliament-works/parliament-at-work/voting-in-parliament/

**Comment by Taz17** [comment]
Closing this issue as PR #1296 has been merged.
