### ISSUE TITLE
December 2021 divisions not uploaded

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/publicwhip#1303]
The divisions that occurred on 1 & 2 December 2021 have not been uploaded to TVFY for either the House or the Senate. The divisions that occurred the day before (30 Nov) uploaded fine.

**Comment by mlandauer** [comment]
Two underlying problems needed fixing:
* One a person was referred to by their official name in the voting record. Fix for that https://github.com/openaustralia/openaustralia-parser/commit/8bcacec859579a6f8520f9657365542aca0d8bf3
* The XML for the members hadn't been regenerated after updating the data a while back by running the parse-members script on openaustralia.org.au.
