### ISSUE TITLE
Rethink/Redesign Twitter cards and Facebook share cards

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/publicwhip#1306]
These were originally put together when the guidelines around image sizes were quite different. We should rethink/redesign the cards with much larger images to take advantage of "the new normal". We did this recently with righttoknow and I think the result is a much improved "sharing" experience with content that stands out much more from the crowd than it used to.

This also could be combined with automated screenshots of that page to immediately show the useful information as people do now on their own.

For Right To Know this is how things look now on Twitter:
![image](https://user-images.githubusercontent.com/2221/146868791-6e2a13ac-b613-4e0d-9efa-e0af0612e089.png)

**Comment by mlandauer** [comment]
There are two different parts to this issue. One of them, which I think is the most important is to create automated screenshots for twitter/facebook shares for the people/policy pages (e.g. https://theyvoteforyou.org.au/people/senate/queensland/nita_green/policies/86). These are the pages that are by far and away the most commonly shared on social media. I'll split that out into a separate issue and keep this issue here for creating a more generic image (similar to righttoknow) for when a user shares any other image.

**Comment by tseyiokorodudu** [comment]
> keep this issue here for creating a more generic image (similar to righttoknow) for when a user shares any other image.

@mlandauer Just to clarify... Currently when an MP's page is shared this is the output. Would this fall under a situation where the more generic image can be used? 

![image](https://user-images.githubusercontent.com/31440427/150240639-8851a15b-72c0-4dee-b51f-9a616e53d132.png)

If yes, my assumption then is, anything that isn't a screenshot of a specific information uses the generic image but the card description & title changes to match the shared page right?

**Comment by mlandauer** [comment]
@tseyiokorodudu I think when sharing a particular person on twitter/facebook we should make a specific image. Right now we're using only a small image for that person as you can see. I do say that in the title for #1316 but perhaps I could be clearer.

As for the second thing, yes I think we sharing a generic image we should change the description and title to match the shared page. That's also what we do in that example from RightToKnow at the top of the issue.

**Comment by mlandauer** [comment]
This issue isn't different enough from #1316 to justify a separate one. I'm going to close this as a duplicate of #1316.
