### ISSUE TITLE
create a clear description for new category status "[Name] Has not voted enough to determine a position on"'

### ISSUE THREAD

**Issue by katska** [openaustralia/publicwhip#1320]
Speaking with @mlandauer he ponders 'Thinking of just making it shorter "Has not voted enough on" - I know you had very sensible issues with that wording. Is there some other version that would be concise yet clear and accurate?'

**Comment by katska** [comment]
Initial thoughts: Not enough

**Comment by katska** [comment]
It may be less pretty - a side thought - that we preface the statement with 'According to our records', while this is far from perfect solution, something like this encourages some discussion of what those records are. The downside is that it's more words and sounds less definitive from the getgo, even when there's a more confident set of data on a position.

**Comment by katska** [comment]
I've been trying hard to think of phrasing in a way that sticks with the format that goes with Name followed by position statement.
Another option @mlandauer raised would be to not show this information at all until there's enough of a record to say something about it.
In discussion just now we agreed it's important to characterise the situation in context so we can depart from the pattern of the other position statements.  Decoupling from that sentence format frees us up, so we could say 'There isn't enough information to characterize X's position on the issue'.

**Comment by mlandauer** [comment]
We've settled for the time being on "We can't say anything concrete about how they voted on"
