### ISSUE TITLE
Add donate button with more targetted ask + redesign footer

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/publicwhip#1322]
With the recent [attacks](https://www.smh.com.au/politics/federal/mps-call-for-partisan-political-transparency-site-to-lose-charity-status-20211108-p5971z.html) against TVFY and the OpenAustralia Foundation including more [constructive criticisms](https://www.oaf.org.au/2021/12/03/productive-discussions-and-pointed-attacks/) there's a renewed interest in donating to and supporting TVFY.

At the moment we just have a tiny, tiny donate link in our footer which is almost impossible to find.

![image](https://user-images.githubusercontent.com/2221/151743704-13e98314-e274-48cc-aa3d-2d28f08b0cd0.png)

Instead let's use a larger donate button in the footer to match the design used in righttoknow.org.au.
Also, we can include some much more targeted wording like
"Help keep They Vote For You trusted and independent"

![image](https://user-images.githubusercontent.com/2221/151743800-0b6ee323-622b-4ec3-afdb-c54d25d2ba69.png)

**Comment by tseyiokorodudu** [comment]
Hi, so I took a stab at this. This is the result.

![image](https://user-images.githubusercontent.com/31440427/156473086-2d9d521a-6b9b-42ae-914c-b76e661860d4.png)

@mlandauer is this what you had in mind?

**Comment by mlandauer** [comment]
@tseyiokorodudu I think that's great!

Looking again at the whole footer on righttoknow I'm struck by the elegance of having the project stuff at the top of footer and then the "extra footer" for the OpenAustralia Foundation stuff. I think it does a really good intuitive job of explaining that the project is run by OpenAustralia Foundation and it has some extra sort of official sounding stuff to make it clear it's a real thing.

![image](https://user-images.githubusercontent.com/2221/157162184-02fdc9aa-2300-409a-bec3-b84d2bd6c7a2.png)

Would it be too much to ask you to have go at rejigging things into that format a little more?

I also think the longer blurb about the site is super-helpful for people that just landed on a random page and have no idea who or what we are.

The longer words could be from the about page "Forget what politicians say. What truly matters is what they do. And what they do is vote, to write our laws which affect us all."
Or it could be something like "Making parliamentary voting information accessible, understandable, and easy to use so that you can hold your elected representatives to account."

**Comment by tseyiokorodudu** [comment]
Sure I can do this. 

Just to confirm ... going by your suggestions we are going to have three footer sections now on the site right? 

1. The TVFY section
2. The OAF section
3. Explore other projects section 
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/31440427/157165282-4175740c-3e22-49fc-a3fc-1162db486798.png">

**Comment by tseyiokorodudu** [comment]
Based on our chat , we've decided on a two footer section (TVFY section & OAF section) and do away with the "other project" section.

**Comment by tseyiokorodudu** [comment]
Here is the rework of the footer 

![image](https://user-images.githubusercontent.com/31440427/157586030-a6e49c59-4148-423b-a2fe-724501d96bbd.png)

@mlandauer feedback please

**Comment by mlandauer** [comment]
* I really like how you've moved the acknowledgement off to the side, rather than under the OAF blurb, which makes much more sense.
* The dark blue links against darker blue are a bit troublesome here I think from a contrast point of view. I have no problem with the links in the footer area working a little differently then the links on the rest of the site.
* I think there's value in trying to be consistent about using the same "OpenAustralia Foundation" branding. So, I'd be keen if the OpenAustralia Foundation was the same image as used on Right To Know. Maybe the words could be "Built and maintained by"
* The words "This data and software are free and open source" seem now a bit out of place. I like how you put the "Report an Issue" in the menu. Maybe get rid of "This data and software are free and open source" and add a link for "Licensing" to that footer menu?

Also, how does the footer behave on mobile?

**Comment by tseyiokorodudu** [comment]
Here we go 

![image](https://user-images.githubusercontent.com/31440427/158268874-7f002525-3d61-4be2-bab1-d6516551a376.png)

For the dark blue links within the descriptions, I changed the colour to white and then made it a different font-weight from the other text, like it is in the Right to Know site.

What do you think of the different font-weight I used for the site description and OAF description?

Also, should the ABN number be on a separate line? 

And this is how it looks on mobile 

![image](https://user-images.githubusercontent.com/31440427/158269758-5f347f08-5d11-4b46-9101-caa3eb959651.png)

**Comment by mlandauer** [comment]
Fixed by #1398
