### ISSUE TITLE
Investigate any potential missing divisions for 2021

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/publicwhip#1331]
Looking at the whole calendar for 2021 on openaustralia.org.au:
* [Representatives](https://www.openaustralia.org.au/debates/?y=2021)
* [Senate](https://www.openaustralia.org.au/senate/?y=2021)

The days on the calendar that are darker but not underlined are the ones where the parliamentary calendar suggests there should have been debates but we haven't got any for one reason or another. I can see a few of those for both houses. This suggests that we might be missing speeches and divisions for 2021.

@mackaymackay any chance you could investigate a little further and see if this is a real problem and if so which days need fixing for which houses?

Let me apologise in advance if you've already let me know about some of these problems in other tickets but I haven't addressed them.

**Comment by mlandauer** [comment]
I forgot to mention this comes of the back of looking at and fixing #1303

**Comment by mackaymackay** [comment]
Good catch!

I've taken a look and we are missing divisions from the following days from both the House and Senate:

- 24 Feb 2021
- 17 Jun 2021
- 29 Nov 2021

I've looked at recess.php and can't see any error that could explain these gaps.

But interestingly, there is an error in recess.php for 2021: the House sitting week 24-27 May is currently keyed in as a recess period. However, the divisions/debates for those days were still uploaded fine and appear on the site. Should I correct recess.php for that week, or leave it as the data uploaded anyway?

**Comment by mlandauer** [comment]
That should be fixed now. You can see the updated divisions at:
* https://theyvoteforyou.org.au/divisions/all/2021-02-24
* https://theyvoteforyou.org.au/divisions/all/2021-06-17
* https://theyvoteforyou.org.au/divisions/all/2021-11-29

**Comment by mlandauer** [comment]
@mackaymackay see above
