### ISSUE TITLE
Programmatically screenshotting and saving social media sharing cards.

### ISSUE THREAD

**Issue by Taz17** [openaustralia/publicwhip#1338]
To capture and screenshot the social media cards programmatically we will be using a headless browser to do so.

Ideally this would be in a rake task so that it can be run frequently to make sure every new social card is captured.

**Comment by Taz17** [comment]
With this implementation comes the issue of where to save the screenshots of the cards. Saving the cards to the VM's harddisk is an option but I don't believe it would be sustainable as this could take up too much memory and slow down the machine. @mlandauer any ideas as to how to store the screenshots?

**Comment by mlandauer** [comment]
> With this implementation comes the issue of where to save the screenshots of the cards. Saving the cards to the VM's harddisk is an option but I don't believe it would be sustainable as this could take up too much memory and slow down the machine. @mlandauer any ideas as to how to store the screenshots?

There's two separate issues here:
1. How much disk space are all the rendered images going to take up?
2. How much memory is needed to generate the images and how long will it take?

The first part isn't much of an issue I think. Disk space is pretty cheap. We can add an extra network mounted disk on the VM without too much trouble. We do something similar on Right To Know which has a lot of space on the machine for storing all the FOI documents. Nevertheless it would be extremely helpful if you could put together an estimate of how much disk space would be needed.

For the second part this could potentially be done in the middle of the night if it doesn't take too long and doesn't require our VM to be spec'd significantly differently. Again please figure out an estimate of the memory needed. I asked for this before. It's really important.

**Comment by Taz17** [comment]
I can give you for an maximum amount of storage required for the screenshots of members and their vote for a particular policy. Their social card can be seen in issue #1339 (600x350 pixels)

Storage for all members and their vote on a policy = no. of all people * no. of all policies * no. bytes for 1 image.
= 227 * 226 * 65931 bytes
= 3382392162 bytes
= 3.38 gigabytes.

As for the other cards i cannot provide and estimate as I don't how many they are

**Comment by Taz17** [comment]
Well given that storing to disk is a valid option, is the naming pattern `MemberID_PolicyID` sufficient?

eg. `production-screenshots/10001_1` for Tony Abbott on poilcy 1.

I assume it will be as it'll be unique and easy to query/search for.

**Comment by mlandauer** [comment]
> As for the other cards i cannot provide and estimate as I don't how many they are

Why can't you provide an estimate of the other cards? What information are you missing? Don't you have an estimate of the number of people and the number of policies. Isn't that enough?

Also, you @Taz17 you haven't answered my question about the memory usage of creating a screenshot and a rough estimate of the amount of time it might take.

**Comment by Taz17** [comment]
My bad @mlandauer, I got carried away with disk memory.

With why I cant provide an estimate for other cards, I don't know how many cards we will have for other pages. For example when sharing a policy, like this one https://theyvoteforyou.org.au/policies/86, im not certain about how many cards a page like this would need. Because you can share the entire policy page or in another case when the user wants to share the section of the policy page for example the `voted consistently for` section. It even has a section called `We can't say anything concrete about how they voted on` which we are yet to discuss what we will do with that.

With regards to memory usage, I measured how much memory is needed by the rake task. It consistently used 695 MB to 709 MB. 

This number does not include the memory usage the actual server will use whilst responding to the requests but does include the headless browser.

For reference, to estimate the memory usage i used the command `pmap` over `ps`. This [stackoverflow question](https://stackoverflow.com/questions/131303/how-can-i-measure-the-actual-memory-usage-of-an-application-or-process) mentions why `ps` is inaccurate.

**Comment by mlandauer** [comment]
@Taz17 like I mentioned earlier, if you can come up with an estimate based on a guess of some of those numbers. So for instance you could estimate that there 10 different versions of the card (one for "voted consistently for", one for "we can't say anything...", etc.) and then you could calculate a reasonable first estimate which will be at the high end but in this case it's better to overestimate rather than underestimate.

The memory usage is really good to know. Thanks. Not as bad as I thought it might be actually. :-)

**Comment by mlandauer** [comment]
I'm going to have a quick go at estimating the disk usage:

First some relevant numbers:
* Overestimate of size of one image: 100kb
* Number of different cards for each policy and for each person: 10
* PolicyPersonDistance.count: 48243
* Policy.count: 281
* Person.count: 951

So, a guess at the number of cards would be
```
PolicyPersonDistance.count + Policy.count * 10 + Person.count * 10 = 60563
```

So then the total required disk space is approximately 6GB

So let's provision an extra 10GB disk then for the server

**Comment by mlandauer** [comment]
The rake task has been rolled out to production. When running it manually it fails after half an hour or so also temporary locking up the server. So far haven't been able to reproduce the problem locally. I'll attach more information to this issue when I have it.

**Comment by mlandauer** [comment]
Here's an example from it failing last week when running manually on the production server:
```
deploy@ip-172-31-3-170:/srv/www/production/current$ RAILS_ENV=production bundle exec rake application:generate:cards
DEPRECATION: :dalli_store will be removed in Dalli 3.0.
Please use Rails' official :mem_cache_store instead.
https://guides.rubyonrails.org/caching_with_rails.html
rake aborted!nshots: |========                                                                                               |  ETA: 01:43:01 Time: 00:09:01
Error Net::ReadTimeout while screenshotting url: https://theyvoteforyou.org.au/people/representatives/robertson/belinda_neal/policies/13?card=true
/srv/www/production/releases/20220310015925/app/lib/card_screenshotter/utils.rb:31:in `rescue in screenshot'
/srv/www/production/releases/20220310015925/app/lib/card_screenshotter/utils.rb:26:in `screenshot'
/srv/www/production/releases/20220310015925/app/lib/card_screenshotter/utils.rb:22:in `screenshot_and_save'
/srv/www/production/releases/20220310015925/app/lib/card_screenshotter/members.rb:21:in `update_screenshot'
/srv/www/production/releases/20220310015925/app/lib/card_screenshotter/members.rb:14:in `block in update_screenshots'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:70:in `each'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:70:in `block in find_each'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:222:in `loop'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:222:in `in_batches'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:69:in `find_each'
/srv/www/production/releases/20220310015925/app/lib/card_screenshotter/members.rb:13:in `update_screenshots'
/srv/www/production/releases/20220310015925/lib/tasks/application.rake:183:in `block (3 levels) in <main>'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'

Caused by:
Net::ReadTimeout: Net::ReadTimeout with #<TCPSocket:(closed)>
/srv/www/production/shared/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/default.rb:124:in `response_for'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/default.rb:77:in `request'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:588:in `execute'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/bridge.rb:93:in `get'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/navigation.rb:32:in `to'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/common/driver.rb:143:in `get'
/srv/www/production/releases/20220310015925/app/lib/card_screenshotter/utils.rb:27:in `screenshot'
/srv/www/production/releases/20220310015925/app/lib/card_screenshotter/utils.rb:22:in `screenshot_and_save'
/srv/www/production/releases/20220310015925/app/lib/card_screenshotter/members.rb:21:in `update_screenshot'
/srv/www/production/releases/20220310015925/app/lib/card_screenshotter/members.rb:14:in `block in update_screenshots'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:70:in `each'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:70:in `block in find_each'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:222:in `loop'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:222:in `in_batches'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.0.4.6/lib/active_record/relation/batches.rb:69:in `find_each'
/srv/www/production/releases/20220310015925/app/lib/card_screenshotter/members.rb:13:in `update_screenshots'
/srv/www/production/releases/20220310015925/lib/tasks/application.rake:183:in `block (3 levels) in <main>'
/srv/www/production/shared/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => application:generate:cards
(See full trace by running task with --trace)
```

**Comment by mlandauer** [comment]
At least the exception got caught `Error Net::ReadTimeout while screenshotting url: https://theyvoteforyou.org.au/people/representatives/robertson/belinda_neal/policies/13?card=true` and checking that url it's all fine so it's nothing to do with what's being screenshotted as such.

**Comment by Taz17** [comment]
This is closed by `Net::ReadTimeout: Net::ReadTimeout with #<TCPSocket:(closed)>` so I think we should find a way to check if the socket is still open.

**Comment by mlandauer** [comment]
I've added a little hack in 8e2a544a41b171cb2d623d781d91a08bceb4f0e7 to close the chrome browser every 50 requests to see if that would make anything better. So far so good. It's now 50% of the way through and it hasn't failed yet. I'm also watching things with `htop` and I can see the memory going up for a little bit then dropping down and then going up and then dropping down.

**Comment by Taz17** [comment]
Mhm That might work, since creating a new driver every 50 requests might get rid of what ever is slowing it down.

There's an issue on selenium's repository with the same error message. https://github.com/SeleniumHQ/selenium/issues/7563

A solution was to increase the `read_timeout`, the default is 60 seconds.

However, increasing the timeout does not answer the question of what is causing it to wait so long? What is happening behind the scenes that is "clogging" the driver that much

**Comment by mlandauer** [comment]
> There's an issue on selenium's repository with the same error message. [SeleniumHQ/selenium#7563](https://github.com/SeleniumHQ/selenium/issues/7563)
> 
> A solution was to increase the `read_timeout`, the default is 60 seconds.

There would be something seriously wrong if the web page was taking 60 seconds to load. So that's not a solution in this case :-)

**Comment by mlandauer** [comment]
Awesome after the hack in 8e2a544a41b171cb2d623d781d91a08bceb4f0e7 it went through all the screenshots in production without error. It took 2 hours and 4 minutes all up.

**Comment by mlandauer** [comment]
Added cron job to run this at night in https://github.com/openaustralia/infrastructure/commit/afa6d353d6ac3c7c7a07f883a13bf82eb9b9c773. I think we can call this closed now
