### ISSUE TITLE
Multiple TVFY policy subscriber emails for single update

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/publicwhip#1342]
I made a small update to a policy this morning - changing a division policy connection from No to No(strong) - and I've so far received five emails telling me the policy has been updated (I'm a subscriber). 

All of the emails are identical. The change I made took place at 8.14 AEDT and the emails have come through at 8.21, 8.21, 8.22, 8.24 and 8.29 AEDT. It's now 8.39 AEDT and no more have arrived so hopefully they have stopped at five.

**Comment by mackaymackay** [comment]
I spoke too soon - a sixth just came in at 8.40 AEDT

**Comment by mackaymackay** [comment]
Seventh at 9.02 AEDT. It seems that the spacing between them is growing.

**Comment by mackaymackay** [comment]
As a last update, emails no. 8, 9 and 10 came in at 9.43, 10.52 and 12.42 AEDT respectively.

**Comment by mlandauer** [comment]
This was fixed by fixing #1344
