### ISSUE TITLE
Make 'reverse ordering' an option on policy page

### ISSUE THREAD

**Issue by mackaymackay** [openaustralia/publicwhip#1343]
We've received an email making the following design suggestion for the policy pages: 

> I do think it could be improved by reverse ordering, starting at what the vote consistently against.  This would much more clearly show who is
>
> Blocking integrity legislation
> Blocking climate action.
> Undermining wages and social services.
> 
> Many people dont read to the end and this I feel is the most important/powerful part.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4el39)

**Comment by mlandauer** [comment]
I agree that this should be an option on the page and not the default (as suggested in the email). The original idea of ordering with "agreement" first was just based on the idea that the sight shouldn't be purely about focusing on people that are against something, which is obviously a bit negative.

**Comment by mlandauer** [comment]
This is now done. An issue that this brings into relief can be seen by looking at a screenshot

![image](https://user-images.githubusercontent.com/2221/154888993-c9e36f79-213e-4ee2-aade-ad44632edc88.png)

The title of the page says "For a citizenship test" but the wording of the first section is "Voted consistently against..."

The page is not really about being **for** a citizenship test. It's about the "citizenship test" and those that are **for** it and those that are **against** it. If we were to remove the word "for" in the title we would also need to add back the clarifying wording around the description which would need to say something like "Those that are "for" this policy believe that people should have to pass a test before they are eligible to become Australian citizens" 

@mackaymackay @katska really would like your thoughts on this before I barge ahead and do something I might regret!

**Comment by katska** [comment]
@mlandauer If you are asking whether its a good idea, then yes, I agree. If you have reservations, would you say more about this so I can better understand?
The idea that pops into my head here is showing them both at once. Two columns side by side. Possibly for the laptop screen but not smaller devices/portrait orientation.

**Comment by mlandauer** [comment]
> If you have reservations, would you say more about this so I can better understand?

My reservation is adding extra words "Those that are "for" this policy believe that..." seems very wordy to me and I don't like the word "believe" but I don't know what else to say.

**Comment by mlandauer** [comment]
I've split out the issue in #1348

**Comment by katska** [comment]
We're in a balancing act of brevity and a meaningful description of the act.
How about simply describing the relationship, a vote 'for' this thing is consistent with the view of 'this policy'
Those "for" have voted in support of "the thing"
... is where I've got to so far.
