### ISSUE TITLE
Update quotes (from twitter) on landing page

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/publicwhip#1345]
They're very old and we can probably find some great ones with all the recent interest

**Comment by mlandauer** [comment]
A few things we could potentially do get some more up to date quotes. We could do one of these or all of these potentially.

* Trawl through twitter for quotes that we can use
* Do a call-out on Twitter asking for people to say nice things
* Do a mail-out to all registered users of the site asking for quotes

**Comment by mlandauer** [comment]
We should do #1346 immediately after this one

**Comment by katska** [comment]
have a go with zotera to look through for these

**Comment by mlandauer** [comment]
It's actually really hard to find quotes, at least on twitter, that aren't super political in their support of TVFY. I guess that shouldn't be surprising. People are using it to defend and broadcast their political position. That's what it's for but we don't want to use any of that in our "this is why I used TVFY and it's useful to me" quotes on the landing page.

**Comment by mlandauer** [comment]
Did a call out on Twitter https://twitter.com/TheyVote4You/status/1510802705664524290

**Comment by katska** [comment]
hmm @mlandauer interestingly not so many replies so far. I wonder if people don't want to be quoted?

**Comment by mlandauer** [comment]
I think doing another callout today would be a good thing

**Comment by mlandauer** [comment]
I did another call out today. I think it's time to do the update with the things we have

**Comment by katska** [comment]
@mlandauer Since there has been a bunch of coverage lately, how about using news media quotes also?

**Comment by mlandauer** [comment]
> @mlandauer Since there has been a bunch of coverage lately, how about using news media quotes also?

@katska can you pick out bits that you like, please?

**Comment by katska** [comment]
_No bells or whistles and nothing dodgy, its an open source platform.
How they actually voted, not just what they said on twitter_
Sarah Wilson
https://www.instagram.com/tv/Cb6_kXyDpfA

**Comment by katska** [comment]
"One website is forcing MPs to put their money where their mouths are by sharing how they vote on the issues." https://news.com.au/national/this-website-will-tell-you-what-your-mp-voted-for/news-story
OR
"one website is holding your local Members of Parliament accountable and taking an ‘actions speak louder than words’ approach, by showing how they voted on the issues"
https://www.news.com.au/national/this-website-will-tell-you-what-your-mp-voted-for/news-story/9e48918aa62ac5c4f196b5e53e4339ec
Kassia Byrnes, Youth Editor News.com.au

other possible recent sources 
https://www.theguardian.com/australia-news/2022/mar/25/liberal-andrew-bragg-accused-of-showing-disdain-for-free-speech-with-legal-threat-to-they-vote-for-you-site
https://www.smh.com.au/politics/federal/pack-of-lies-liberals-take-legal-action-over-they-vote-for-you-site-20220322-p5a6wm.html 
https://www.tiktok.com/search?q=theyvoteforyou&t=1649303304103

**Comment by mlandauer** [comment]
Still need to let everyone whose quotes we used know

**Comment by mlandauer** [comment]
Let them know in https://twitter.com/TheyVote4You/status/1513327922693611521
