### ISSUE TITLE
Policy detail page currently has title "for" a policy but that isn't strictly true

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/publicwhip#1348]
Look at the following screenshot

![image](https://user-images.githubusercontent.com/2221/154888993-c9e36f79-213e-4ee2-aade-ad44632edc88.png)

The title of the page says "For a citizenship test" but the wording of the first section is "Voted consistently against..."

The page is not really about being **for** a citizenship test. It's about the "citizenship test" and those that are **for** it and those that are **against** it. If we were to remove the word "for" in the title we would also need to add back the clarifying wording around the description which would need to say something like "Those that are "for" this policy believe that people should have to pass a test before they are eligible to become Australian citizens" 

@mackaymackay @katska really would like your thoughts on this before I barge ahead and do something I might regret!

_Originally posted by @mlandauer in https://github.com/openaustralia/publicwhip/issues/1343#issuecomment-1046462835_

**Comment by katska** [comment]
@mlandauer umm. crazy idea. how about we remove the word FOR. Then only the issue subject matter remains. Or use the word On instead. 
Having discussed this with @mlandauer just now there are a few of different issues here. I'm going to look to see what's been separated out and then come back in with further suggestions

**Comment by mackaymackay** [comment]
@mlandauer to be honest, I'm not seeing the wording issue here. It may be that I read the word "for" differently? As in, I see it as a fairly broad word meaning something like 'in favour of' or 'wanting'.

Did you want to reword the policy to something like "for requiring prospective citizens to take a citizenship test"? Would that solve the issue?

**Comment by mlandauer** [comment]
I understand the meaning of "for" in the same way - that one is "in favour of".

I probably didn't do a good enough job of explaining what I meant with the issue specifically. Let me have another go. 

I'm going to paraphrase what the particular policy page (https://theyvoteforyou.org.au/policies/166) above says right now

## For a citizenship test
### John Alexander voted consistently for a citizenship test
### Anthony Albanese voted consistently against a citizenship test 

This is the suggestion for how the page should be changed

## A citizenship test
### John Alexander voted consistently for a citizenship test
### Anthony Albanese voted consistently against a citizenship test 

The problem that we're trying to address is that the heading "For a citizenship test" doesn't make sense because the page is showing that Anthony Albanese is **against** the citizenship test. On the page we're showing people that are both **for** it and **against** it.

So, it makes sense to remove the word "for" from the heading so the page is about "A citizenship test". Does that make sense?

Oh and one thing I haven't said before is that the word "for" is actually currently put in by the application. So making this change wouldn't need to involve editing any of the policy wording.

**Comment by mackaymackay** [comment]
Ok, I think I'm getting it now. I agree with removing the 'for' from the heading. I don't think it will cause problems with any of the policies, but if you'd like me to do a double-check, I can do that next week.
