### ISSUE TITLE
Fix logging and extra javascript tag in policy with member card

### ISSUE THREAD

**Issue by Taz17** [openaustralia/publicwhip#1352]
Its unnecessary to have `= javascript_include_tag  "card"` line [19](https://github.com/openaustralia/publicwhip/blob/master/app/views/card/policy_with_member_card.html.haml#L19).

As well as the logging to the console that was used whilst debugging in line [22](https://github.com/openaustralia/publicwhip/blob/master/app/views/card/policy_with_member_card.html.haml#L22)

**Comment by mlandauer** [comment]
@Taz17 good catch
