### ISSUE TITLE
Put site explanation from about page onto landing page

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/publicwhip#1382]
On the about page https://theyvoteforyou.org.au/about we say "Forget what politicians say. What truly matters is what they do. And what they do is vote, to write our laws which affect us all." which is a clear explanation of the intent and scope of the site. Most people will likely never see this on the about page.

Why don't we put it on the landing page as well below the first main section "How does your MP vote on the issues that matter to you?"

**Comment by katska** [comment]
good idea yes!
