### ISSUE TITLE
Search results not showing People on full name

### ISSUE THREAD

**Issue by katska** [openaustralia/publicwhip#1393]
Search results not showing People on full name
Example: Search Andrew Wilkie, only divisions appear
<img width="915" alt="Screen Shot 2022-04-06 at 10 43 09 am" src="https://user-images.githubusercontent.com/1001129/161873647-1f5d6ee3-8d55-4080-b6aa-ed406cf33a5a.png">

vs search Wilkie where People results correctly come first
<img width="960" alt="Screen Shot 2022-04-06 at 10 43 16 am" src="https://user-images.githubusercontent.com/1001129/161873652-4cb3f59c-a3be-48fa-a215-6d3f92bd8c9d.png">

**Comment by mlandauer** [comment]
Note that the search on the landing page works differently. When you put "Andrew wilkie" in there you get immediately directed to his page
