### ISSUE TITLE
Social card 6: General Card (Sharing the site from homepage)

### ISSUE THREAD

**Issue by tseyiokorodudu** [openaustralia/publicwhip#1394]
This is the design I have for the general card. Keeping with the site design, I have kept it simple and spacious. 

![General](https://user-images.githubusercontent.com/31440427/161873377-7e81d613-f4dd-4866-be02-4864f651066f.png)
 
@mlandauer @katska @Taz17 thoughts? Should I increase the font size a bit?

Also @mlandauer this card is going to be an image and not coded like the other cards right?

**Comment by mlandauer** [comment]
> Also @mlandauer this card is going to be an image and not coded like the other cards right?

Like I said in person, an image of the correct size added to the assets folder is great. Could you also please commit the original illustrator file (or whatever you used for design) so this could be edited later. Thank you!

**Comment by mlandauer** [comment]
Fixed by #1400
