### ISSUE TITLE
Reinstate mp comparison pages

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/publicwhip#255]
The mp comparison pages were removed in b0d1a6fdaf31b6b437332fc9baf8e8ec6116dd36. This was because there was a bad bug in php version of the page which meant that it would show mps as not having voted differently in divisions when in fact they did.

It proved too difficult to try to fix the php implementation (without breaking anything else of course).

The mp comparison pages are not the easiest page to find anyway. It's what you get to get when you click on a percentage agreement in a list of mps such as the "possible friends" table.

In the name of moving forward we've removed the links to those pages. The aim of this ticket is to add the feature back in. Probably best to do it when the rails code has been refactored a bit more. The current implementation of the mp comparison has not been removed. So, it will be still be there for reference.

**Comment by nkavadias** [comment]
I'd like to see this feature added back.

**Comment by henare** [comment]
Context: https://twitter.com/nkav/status/722983986373357568

**Comment by brtrx** [comment]
Is there a screenshot / wireframe of the removed feature?

**Comment by henare** [comment]
You can see it in action on the UK site: http://www.publicwhip.org.uk/mp.php?mpn=David_Cameron&mpc=Witney&house=commons&mpn2=Jeremy_Corbyn&mpc2=Islington_North&house2=commons

**Comment by mlandauer** [comment]
Gosh I had totally forgotten that we had to remove this feature!

**Comment by mlandauer** [comment]
Duplicate of #1251
