### ISSUE TITLE
Email alerts on wiki pages getting updated

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/publicwhip#308]
When you edit a wiki page you could optionally (with a default of yes) get email alerts when someone else changes the wiki text. This could help combat bad things

**Comment by mackaymackay** [comment]
Hi @mlandauer I tend to use the [recent edits](https://theyvoteforyou.org.au/history) page to keep track of changes made by users. I suspect that emails about updates would just get lost in the inbox, as I would get so many on each day that I'm doing updates that I'd probably stop paying any attention to them, which would defeat their purpose.

That said, did we stop sending out emails for subscribers to policies? It suddenly occurs to me that I've not seen one of those emails in a while, despite being a subscriber to all active policies, and now I'm not sure if I set it so I no longer get emails myself (and just forgot I did that), or if they've stopped going out altogether..?
