### ISSUE TITLE
Clarify policy agreement language (i.e. strong vs. normal vote)

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#371]
Currently the app says, [for example](http://publicwhip-rails.openaustraliafoundation.org.au/policies/7), "Aye (strong)".

I think "strong" is the wrong language because if you have a look at a [policy agreement calculator](http://publicwhip-rails.openaustraliafoundation.org.au/mp.php?dmp=7&house=representatives&mpc=Warringah&mpn=Tony_Abbott#ratioexpl) "strong" really means normal and non-strong is for a procedural vote.

**Comment by mlandauer** [comment]
I think we improved the language around this
