### ISSUE TITLE
Rework electorate page to negate need for notice about data limits

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#433]
On this page we have a big sentence about how far our data goes back: http://publicwhip-rails.openaustraliafoundation.org.au/members/representatives/griffith

Why not just display it if we are displaying partial data for a member? e.g. only show a row for a member if we have at least partial data for them. On that page ☝️ Graeme McDougall 	is the MP we have no data for. If we have an MP that we have partial data for, which is because were a member both before and after 2006, then we should show the notice.

For that page we could just get rid of the last row (#432) then we don't even need that sentence.

**Comment by Tanuja-Sawant** [comment]
@equivalentideas may I take this up?

**Comment by henare** [comment]
@Tanuja-Sawant I've reviewed this issue and I think I was trying to be too smart :wink: The way it currently works looks OK to me so I'll close this issue as wont-fix.

**Comment by Tanuja-Sawant** [comment]
@henare Okay thank you, I'll pick up another issue
