### ISSUE TITLE
Punctuation in division titles is inconsistent

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/publicwhip#555]
Sometimes an em dash is used, other times a semicolon to separate sections of the unedited division title:

> Bills — Fair Work Amendment Bill 2014; Second Reading

The researchers have consistently changed this to be all em dashes. Could the app make that change ahead of time? Would make this more consistent, speed up comprehension.

**Comment by Tanuja-Sawant** [comment]
@equivalentideas may I take this up?

**Comment by Tanuja-Sawant** [comment]
Where is this unedited division title located?

**Comment by equivalentideas** [comment]
@Tanuja-Sawant It comes out of the database.
