### ISSUE TITLE
add link to set of principles speaker is supposed to act on when casting deciding vote

### ISSUE THREAD

**Issue by kat** [openaustralia/publicwhip#645]
at http://publicwhip-rails.openaustraliafoundation.org.au/help/faq#tied-division

**Comment by cofiem** [comment]
Here's an initial go at the Speaker's principals when voting due to a tie:

(Note: remove the crossed out `always`)

> In the House of Representatives, the Speaker [does not vote](https://peo.gov.au/understand-our-parliament/how-parliament-works/parliament-at-work/voting-in-parliament/) unless the result is a tie, in which case [the Speaker has the casting vote](http://www.aph.gov.au/about_parliament/house_of_representatives/powers_practice_and_procedure/%7E/link.aspx?_id=8485A681FB314882871407C0A81BE62C&_z=z#thesp) to decide the matter. Speakers are expected to cast their vote according to a set of principles but these have not **~always~** been applied consistently (of course!).

> **The [three principals](https://www.aph.gov.au/About_Parliament/House_of_Representatives/Powers_practice_and_procedure/Practice7/HTML/Chapter6/The_Speaker%27s_vote) are 1) that the Speaker should allow further discussion if possible, 2) that the majority should agree to any actions or changes, so the Speaker's vote should stop the actions or changes, and 3) particularly for a change to a bill, the Speaker's vote should keep the bill as it is.**

> There are also rare cases where the Speaker has not exercised a casting vote. For example when a vote that [requires an absolute majority](http://www.aph.gov.au/about_parliament/house_of_representatives/powers_practice_and_procedure/%7E/link.aspx?_id=9401351F60524BBF93050639FBA28300&_z=z#abs) is tied, the Speaker’s casting vote may not achieve an absolute majority so there’s no reason for them to exercise that vote.

> In the Senate, the President of the Senate may always vote along with other senators so they do not have a casting vote. If a vote in the Senate is tied it is [considered to have failed](https://peo.gov.au/understand-our-parliament/how-parliament-works/parliament-at-work/voting-in-parliament/) because a majority vote has not been reached.
