### ISSUE TITLE
Add intro par with interesting pieces to divisions#show

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/publicwhip#664]
A short intro sentence that pulls out the some of the key data from the division.

> The majority voted to reject the motion in this division and there were no rebellions. This division relates to the policies 'agricultural biosecurity' and 'a carbon tax' and there was an above average turn-out.

if it's a member comparison:

> Tony Abbott voted ‘no’ with the majority in this division, no-one rebelled.
> This division relates to the policies 'agricultural biosecurity' and 'a carbon tax'. There was an above average turn-out.

**Comment by mlandauer** [comment]
Thanks @mackaymackay. In the case I'll close this as a won't fix.
