### ISSUE TITLE
highlight unusual divisions in index

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/publicwhip#682]
We add a visual cue to highlight unsummarised divisions where something unusual has happened, to draw more attention to them so citizens go and summarise them.

For example divisions with unusually high or low attendance, or if there is a rebel vote.

**Comment by uma-1602** [comment]
Hey @equivalentideas ! Since I mentioned that I am a beginner, can you please guide me that is this issue fit to be taken up as a first contribution? 
If yes, tell me which directory or file should be hacked?

**Comment by henare** [comment]
Hi @uma-1602, thanks for your interest! :raised_hands: There's a few things that need to be worked out to do this, e.g. what makes an usual division? what are the different ways we want to highlight these?

For this reason I don't think this is a great issue to tackle as a first contribution. I'll remove the label, thanks for asking first :smile:
