### ISSUE TITLE
Related divisions intro copy should list the related bill/bills

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/publicwhip#751]
> Because they relate to the same bill as this division

could be:

> Other divisions related to the _National Security Legislation Amendment Bill (No. 1) 2014_

For example on: https://theyvoteforyou.org.au/divisions/senate/2014-09-25/7

Not sure what to do if there are lots of bills, but I think it's useful even if just implemented for single bill situations for now.

**Comment by mlandauer** [comment]
I think we actually do this now. So, closing.
