### ISSUE TITLE
Add count of number of people in each section for a policy

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#866]
https://theyvoteforyou.org.au/policies/47 e.g. 26 people voted very strongly, etc.

**Comment by avaldivi** [comment]
Hello I would like too see if this is eligible to work on for my first PR for my outreachy application or should I look at another issue? @equivalentideas

**Comment by equivalentideas** [comment]
> Hello I would like too see if this is eligible to work on for my first PR for my outreachy application or should I look at another issue? @equivalentideas

Sounds good @avaldivi 👍 In your PR it would be great to see a screen shots of what the email looks like in different situations.
