### ISSUE TITLE
Hide/unhide arrows do not flip when content opens leading to poor UX

### ISSUE THREAD

**Issue by bbqsrc** [openaustralia/publicwhip#870]
The little arrows that allow you to show more content don't flip to point up when content is showing, making it unclear that pressing it again will allow you to hide the content, while also implying there is more content available if you click it again.

Example:
https://theyvoteforyou.org.au/divisions/senate/2014-09-30/8

Screenshot:
![screen shot 2014-10-21 at 14 26 31](https://cloud.githubusercontent.com/assets/279099/4712692/17d7bde2-58d2-11e4-8f77-e904cd53623d.png)

You can see both arrows pointing down, while only one of them has been clicked to show content. :smile:

**Comment by equivalentideas** [comment]
I implemented this downstream on https://rada4you.org, check it out here https://rada4you.org/divisions/rada/2017-03-21/11304

This looks like the commit (it was a while back). https://github.com/OPORA/publicwhip/commit/22d4dd23138a50e96613257b8cad00cb90930fa3

Would this fix just involve cherry-picking that over?

**Comment by henare** [comment]
>Would this fix just involve cherry-picking that over?

Yep 49d3ae3.
