### ISSUE TITLE
Vote importance headings in table in the `How "voted strongly for" is worked out` section needs highlighting

### ISSUE THREAD

**Issue by mithro** [openaustralia/publicwhip#876]
On pages like https://theyvoteforyou.org.au/people/representatives/sydney/tanya_plibersek/policies/3#ratioexpl in the `How "voted strongly for" is worked out` section there is a table which shows how the points are calculated.

In the first column there are headings like "Most important votes (50 points)" which separate out the calculations. These labels at first glance don't stand out making the table slightly confusing. They could use some bolding or other differentiator from "MP voted xxx policy" labels.

**Comment by mlandauer** [comment]
There are a whole bunch of issues that are looking at the problem of explaining the policy agreement summary and how it's calculated and finding ways to improve it.

**Comment by mlandauer** [comment]
I think the change in #1271 could help make this all much more obvious. It also provides a very logical place to explain how "strong" votes are weighted into the overall calculation and what they mean. I'll leave this issue open until that all becomes clearer.

**Comment by mlandauer** [comment]
The change in b7b51a0b1a76ffae4676a901036c69cab76bbe94 and a switch to a (I think) clearer and more direct explanation involving scores and weights goes a long way to making things a bit better
