### ISSUE TITLE
Make API Popolo compatible

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#919]
http://www.popoloproject.com/specs/vote.html

**Comment by henare** [comment]
When we do this we should make sure you can just page through every division, see https://github.com/OPORA/publicwhip/issues/154

**Comment by KrzysztofMadejski** [comment]
+1 for that, let's use one standard to rule all them MPs

**Comment by mlandauer** [comment]
Playing devil's advocate here are there any tools out there in the wild that could make use of the data out of the box if we provided a compatible API?
