### ISSUE TITLE
create useful fallback for when mp images don't load.

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/publicwhip#947]
If there is a problem with loading MP images on a policy, the result is very unhelpful.

![screen shot 2014-11-20 at 10 01 09 am](https://cloud.githubusercontent.com/assets/1239550/5116257/46c19d30-709c-11e4-8342-b18bb3655767.png)

**Comment by jamezpolley** [comment]
These photos now have an Alt text "Photo of $NAME" so this seems to be resolved.
