### ISSUE TITLE
After a policy is updated, the member positions for it are all mixed up (are wrong) while they are rebuilt/recalculated for a few minutes

### ISSUE THREAD

**Issue by henare** [openaustralia/publicwhip#982]
We currently show positions which are simply wrong. Even though it's only for a minute or two we can do better.

**Comment by drzax** [comment]
I saw this in the wild today. After linking [a division](https://theyvoteforyou.org.au/divisions/senate/2016-08-31/2) to [a policy](https://theyvoteforyou.org.au/policies/60). I visited the policy page to find some unexpected results:
![screen shot 2016-09-01 at 10 00 38](https://cloud.githubusercontent.com/assets/596563/18157177/19f85496-705f-11e6-95f3-a866c83094a1.png)

The issue fairly quickly resolved itself.

**Comment by equivalentideas** [comment]
I've updated the title of this to report the problem, rather that a possible solution. This should make it easier for people to find.

**Comment by mlandauer** [comment]
I think this probably also occurs when the daily rake task is run at 10am or so.

**Comment by mlandauer** [comment]
When a policy division is added/changed/deleted `calculate_person_distances!` (https://github.com/openaustralia/publicwhip/blob/9bf41831d92e3f5cfb09131d479f56162dd9a0e7/app/models/policy.rb#L59) is run in the background. The first thing it does in this current implementation is delete all the cached person distance measures for this policy. That's what is causing this problem

**Comment by mlandauer** [comment]
Looks to me like `calculate_person_distances!` is not being tested. So, the first thing to do is to add that. Not an entirely straightforward thing to do unfortunately.

**Comment by mlandauer** [comment]
Fixed by 36bf1f4e89173374071c09ab94367be0c02d17c3
